### ISSUE TITLE
No methods available

### ISSUE THREAD

**Issue by a-zen** [monofox/python-aqbanking#1]
I installed the module with `python3 setup.py install --user`.
After trying the module in the python shell, there are none of the
defined functions like hello or listacc.

Any hints?

**Comment by monofox** [comment]
Hi Alex,

Could you please give me the output of the install command as well as how use the module in the python shell?

**Comment by a-zen** [comment]
Sure here they are.

Installation: 
https://gist.github.com/a-zen/3af99ef04023f42a565b

(simple) Usage:
https://gist.github.com/a-zen/82346a4a57f94ba662c5

**Comment by monofox** [comment]
Hmm just checked also. Can reproduce it. The whole module content is not recognized anymore.

**Comment by monofox** [comment]
Hi Alex,

fixed (yes, hello does not exist anymore -- it was just useless).  

Regards,
Lukas
