### ISSUE TITLE
RuntimeConfigurations like fintsRegistrationKey

### ISSUE THREAD

**Issue by thtomate** [monofox/python-aqbanking#16]
Für FinTS braucht man bei den Banken bald einen Key, dafür muss man bei AqBanking eine Laufzeit-Variable setzen.
siehe: https://github.com/aqbanking/aqbanking/commit/4ddb7f9b6ac363d25b4f1da0a503e8461bb7abdd https://github.com/Gnucash/gnucash/commit/39cfcb30f939ca3c413350c8262ceea69085fb6b#diff-22c8f235e1c329e32752ece748c0c3a4

Ich hätte es schon eingebaut, wenn es einfach wäre, doch ich weiß nicht wo ich das Speichern soll.

**Comment by monofox** [comment]
Danke für den Hinweis @thtomate. Ich denke hier muss der Key für jede Applikation beantragt werden (also sprich: nicht für die Bibliothek selbst). Ich sehe die Bibliothek nicht als Applikation. Ich würde also nur ein "Interface" hier implementieren und die nutzende Applikation hat den entsprechenden Key zu speichern und zu übergeben. Oder siehst Du das anders?

**Comment by thtomate** [comment]
Ja, so sehe ich das auch, ich habe für meine Applikation bereits einen Key beantragt

**Comment by monofox** [comment]
@thtomate : Ich habe ein Bibliothekskey beantragt und werde ihn - wie in den Dokumentationen beschrieben - als Fallback reinkompilieren lassen. So können dann bei Bedarf auch Tests mit den Beispielen ausgeführt werden.
Die neue Funktion ist in AqBanking erst mit der nächsten Version verfügbar. Da wurde einiges umgestrickt. Ich prüfe inwiefern die Abwärtskompatibilität gewahrt werden kann.

**Comment by thtomate** [comment]
> Die neue Funktion ist in AqBanking erst mit der nächsten Version verfügbar

Auch schon mit der aktuellen stabilen Version 5.8.1. Ich glaube die ist aber noch nicht bei Debian in den Repos.

**Comment by monofox** [comment]
Bei Gentoo auch nicht. Ich habe die aktuellen stable Versionen von Gwenhywfar und AqBanking manuell gebaut und getestet:
![image](https://user-images.githubusercontent.com/765309/64012701-77bf6480-cb1e-11e9-9603-6a6014e38033.png)
Die Daten werden korrekt an Gwenhywfar übergeben und auch via HBCI weitergereicht (im HKVVB Segement mit Produktbezeichnung und Produktversion). Allerdings scheint es die Sparkasse noch nicht zu interessieren und die Meldung über die Registrierung erscheint unabhängig davon, ob übergeben oder nicht:
![image](https://user-images.githubusercontent.com/765309/64013231-a68a0a80-cb1f-11e9-8fa6-af8af4062a8e.png)

Ohne Registrierung wurde früher immer AQHBCI übergeben:
```
appname: AQHBCI
appversion: 5.7
```

Ein Setzen des Registriercodes würde dann wie folgt erfolgen:
```python
# in order to consider the new rules in terms of FinTS registration code, you may need to set the
# registration code accordingly:
aqbanking.setRegistrationKey('some characters')
```

**Comment by thtomate** [comment]
Vielen, vielen Dank für die schnelle Lösung! Ich werde es in den nächsten Tagen mal testen.

**Comment by monofox** [comment]
Hmm einer meiner Banken erzwingt nun auch die TAN unregelmäßig via HBCI. Die Consors hatte heute ihre Umstellung. Damit klappt das aber noch nicht so richtig hier (bricht ab, weil hier keine TAN abgefragt und mitgesendet wird). In der AqBanking mailing list wurde geschrieben, dass hier die Konten aktualisiert werden müssen. Vielleicht müssen wir noch ein Dialog/callback mit umsetzen?

**Comment by thtomate** [comment]
Ich glaube dafür braucht man auch noch eine neuere Version von aqbanking.

Der Callback für TANs sollte für alle Vorgänge wie Überweisung und Umsatzabfrage einheitlich sein. Ich habe mir das noch nicht in aqbanking angeschaut

**Comment by thtomate** [comment]
Ach ja, die eigentlich dem Issue betreffende Änderung funktioniert, die Meldung des unregistierten Produktes ist verschwunden und es wird mein Key verwendet.
