### ISSUE TITLE
Segmentation fault in case of using Account from listacc()

### ISSUE THREAD

**Issue by monofox** [monofox/python-aqbanking#2]
Nice mail from a developer retrieved:
if we're trying to use a function directly from listacc()[x] the module segfaults.
The issue is always reproducable. It doesn't matter whether its just set_callback or whether it is a call for retrieving the balance.

Very simple test script:

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import aqbanking
aqbanking.listacc()[2].balance()
```

**Comment by jannh** [comment]
It seems like the calls to _PyObject_New and PyObject_Init are not working. At least, if I put a fprintf at the top of the Account_New or Account_Init functions, I can see no output when running listacc(). 

The segmentation fault results from account->aqh not being set (as Account_init is never executed). It is therefore NULL and trying to access it results in a segfault.

**Comment by monofox** [comment]
Hi jannh. Many thanks for your help. I found the reason! Could you please test it?

**Comment by jannh** [comment]
Thank you for the fix! It works perfectly for me!
