### ISSUE TITLE
How to set password callback?

### ISSUE THREAD

**Issue by elohmeier** [monofox/python-aqbanking#8]
Hello @monofox,
can you help me to use your library?
I'm trying to fetch transactions and account balance.
When using `aqbanking.listacc()[0].balance()` the output contains `No password python CB defined!` and `python3: imexporter.c:1453: AB_ImExporterAccountInfo_GetFirstAccountStatus: Zusicherung »iea« nicht erfüllt.`
I'm using Pin/Tan Authentication, how can I provide my pin using a password callback? How do I register it?

Regards 
Enno

**Comment by monofox** [comment]
Hi Enno,

could you please show me your script to see how you initialize the
aqbanking module? Attached, you can see a script, how to retrieve the
balance (sure, with listacc(), you should also get directly the correct
Account type).

Regards,
Lukas

**Comment by monofox** [comment]
@elohmeier Sorry, attachments are ignored in the mail ;)
Here is the example: https://gist.github.com/monofox/59fbd5fb789040e3731922e8806e6918

**Comment by elohmeier** [comment]
@monofox thanks for the quick reply =)
This is my script:
[https://gist.github.com/elohmeier/e12fec18d975575f7431587946e1373b](https://gist.github.com/elohmeier/e12fec18d975575f7431587946e1373b)

So I've tried your script from the gist, and replaced '<type-your-pw>' with my banks user account pin and also tried the PIN_..._ syntax from the aqbanking pinfile.
Is this correct?
I'm getting the following output: [https://gist.github.com/elohmeier/f5e75486a33ddb07ec1b06c863eca00f](https://gist.github.com/elohmeier/f5e75486a33ddb07ec1b06c863eca00f)

I'm able to sucessfully fetch transactions using 
`aqbanking-cli -n -P pinfile -A request -b **BLZ** -a **KTO** -c transactions.ctx --transactions`.

**Comment by monofox** [comment]
@elohmeier First: i recommend you, to remove the gist again. You're PIN is written their in plain text! In line 189, its saying, that the PIN is wrong (at least it seems so).
Second: i will check and will soon give an answer.

**Comment by monofox** [comment]
Which python version are you using?

**Comment by elohmeier** [comment]
If you mean `[LOG]: 'jobqueue.c:  667: Bad PIN flagged: 9942'
3:2017/02/11 17-21-01:aqhbci(334):jobqueue.c:  667: Bad PIN flagged: 9942` that's not my pin - I've checked the file before uploading, but thanks =)
I'm using python 3.5.

**Comment by monofox** [comment]
OK.. great :) i'll check tomorrow. My banks interface is down for maintenance today and chipcard is not supported yet.

**Comment by monofox** [comment]
Hello @elohmeier
Could you please check the logs in ```~/.aqbanking/backends/aqhbci/data/banks/de/(bank code)/logs``` ?
You could get the exact path by executing the get balance script like this:
```bash
env AQBANKING_LOGLEVEL="verbous" GWEN_LOGLEVEL="verbous" python3 getbalance.py
```
In theory, there sould be some return codes from HBCI interface with the error codes ```9340``` or ```9942```

E.g. if the wrong PIN code is sent to the HBCI interface, i see in the log files:
```
mode: pintan
rdhtype: 1
hbciVersion: 220
tokenType: pintan
crypt: yes
sender: bank
gwenhywfar: 4.15.3.0
aqhbci: 5.6.10.0stable
appname: AQHBCI
appversion: 5.6
size: 172

HNHBK:1:3+000000000172+220+000003PHUA6D95MQ9QSJR2819K78AU+1+000003PHUA6D95MQ9QSJR2819K78AU:1'HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9942::PIN ungültig.'HNHBS:3:1+1'
```

You could also check, what we get from the python script and passing to Gwenhywfar by applying following patch:
```patch
diff --git a/aqbanking/pyaqhandler.cpp b/aqbanking/pyaqhandler.cpp
index 6f16ecc..bf0d1cc 100644
--- a/aqbanking/pyaqhandler.cpp
+++ b/aqbanking/pyaqhandler.cpp
@@ -91,6 +91,7 @@ int PyAqHandler::getPassword(uint32_t flags, const char *token, const char *titl
                passwordPy = PyBytes_AS_STRING(s);
 #endif
                strcpy(buffer, passwordPy);
+               fprintf(stderr, "%s: %s\n", "Password for AQBanking given as", buffer);
                Py_DECREF(result);
        }
```
In that case, you should see - after executing - a line which is saying: 
```
Password for AQBanking given as: xxxxx
````

Could you please try and give a feedback? The correct format for the password callback is definitely just returning the PIN - not the format of the pin file.

Regards,
Lukas

**Comment by monofox** [comment]
Closed as no respond.
